name: Greeting

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet PR
        uses: actions/first-interaction@v1
        if: github.event_name == 'pull_request'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Greet Issue
        uses: actions/first-interaction@v1
        if: github.event_name == 'issues'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
